Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

======== RESTART: C:/Users/Vivek Tiwari/Downloads/PYTHON ASSIGNMENT 3.PY =======


<<<<<QUESTION1>>>>>

ENTER A STRING: HELLO I AM VIVEK
Count of all words in string is :
  {'HELLO': 1, 'I': 1, 'AM': 1, 'VIVEK': 1}


<<<<<QUESTION2>>>>>

A PYTHON PROGRAM TO PRINT NEXT DATE OF INPUT DATE 

ENTER DAY: 31
ENTER MONTH: 12
ENTER YEAR: 2021
The next day is 1 / 1/ 2022


<<<<<QUESTION3>>>>>

Enter number of elements in list:3
Enter a number :24
Enter a number :12
Enter a number :13
[(24, 576), (12, 144), (13, 169)]


<<<<<QUESTION4>>>>>

ENTER YOUR GRADE POINT: 10
Your Grade is A+ and Outstanding Performance.


<<<<<QUESTION5>>>>>

 ABCDEFGHIJK
  ABCDEFGHI
   ABCDEFG
    ABCDE
     ABC
      A


<<<<<QUESTION6>>>>>

ENTER STUDENT's NAME : VIVEK
ENTER STUDENT'S SID : 21104037
DO YOU WANT TO ADD ANOTHER VALUE (Y/N) : Y
ENTER STUDENT's NAME : ANMOL
ENTER STUDENT'S SID : 20000000
DO YOU WANT TO ADD ANOTHER VALUE (Y/N) : N
{'21104037': 'VIVEK', '20000000': 'ANMOL'}
[('20000000', 'ANMOL'), ('21104037', 'VIVEK')]
[('20000000', 'ANMOL'), ('21104037', 'VIVEK')]
ENTER SID OF REQUIRED STUDENT: VIVEK
NAME OF STUDENT:  None


<<<<<QUESTION7>>>>>

How many terms are to be printed in fibonacci series?
6
The Required Fibonacci series is:
 [0, 1, 1, 2, 3, 5] 

Average of following series is:
 2.0 



 <<<<QUESTION 8>>>>
{1, 3, 5, 6, 8}
{17, 3, 6, 8, 9, 13}
{1, 2, 4, 5}
{6, 7, 8, 9, 10}
{10, 7}
